
//! Autogenerated weights for `pallet_acurast_hyperdrive_ibc`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-10-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `acurast-benchmark`, CPU: `AMD EPYC 7B13`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("acurast-kusama")`, DB CACHE: 1024

// Executed Command:
// /acurast-node
// benchmark
// pallet
// --chain=acurast-kusama
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// *
// --extrinsic
// *
// --steps=50
// --repeat=20
// --output=/benchmarks/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_acurast_hyperdrive_ibc`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_acurast_hyperdrive_ibc::WeightInfo for WeightInfo<T> {
	/// Storage: `AcurastHyperdriveIbc::OraclePublicKeys` (r:0 w:50)
	/// Proof: `AcurastHyperdriveIbc::OraclePublicKeys` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 50]`.
	fn update_oracles(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 11_070_000 picoseconds.
		Weight::from_parts(9_612_341, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 3_626
			.saturating_add(Weight::from_parts(2_112_660, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
	}
	/// Storage: `AcurastHyperdriveIbc::MessageCounter` (r:1 w:1)
	/// Proof: `AcurastHyperdriveIbc::MessageCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::OutgoingMessages` (r:1 w:1)
	/// Proof: `AcurastHyperdriveIbc::OutgoingMessages` (`max_values`: None, `max_size`: Some(1256), added: 3731, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::OutgoingMessagesLookup` (r:0 w:1)
	/// Proof: `AcurastHyperdriveIbc::OutgoingMessagesLookup` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	fn send_test_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `4721`
		// Minimum execution time: 73_000_000 picoseconds.
		Weight::from_parts(75_420_000, 0)
			.saturating_add(Weight::from_parts(0, 4721))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AcurastHyperdriveIbc::OutgoingMessages` (r:1 w:1)
	/// Proof: `AcurastHyperdriveIbc::OutgoingMessages` (`max_values`: None, `max_size`: Some(1256), added: 3731, mode: `MaxEncodedLen`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::OraclePublicKeys` (r:1 w:0)
	/// Proof: `AcurastHyperdriveIbc::OraclePublicKeys` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::OutgoingMessagesLookup` (r:0 w:1)
	/// Proof: `AcurastHyperdriveIbc::OutgoingMessagesLookup` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	fn confirm_message_delivery() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `630`
		//  Estimated: `4721`
		// Minimum execution time: 86_510_000 picoseconds.
		Weight::from_parts(88_340_000, 0)
			.saturating_add(Weight::from_parts(0, 4721))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AcurastHyperdriveIbc::OutgoingMessages` (r:1 w:1)
	/// Proof: `AcurastHyperdriveIbc::OutgoingMessages` (`max_values`: None, `max_size`: Some(1256), added: 3731, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::OutgoingMessagesLookup` (r:0 w:1)
	/// Proof: `AcurastHyperdriveIbc::OutgoingMessagesLookup` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	fn remove_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `288`
		//  Estimated: `4721`
		// Minimum execution time: 45_400_000 picoseconds.
		Weight::from_parts(46_320_000, 0)
			.saturating_add(Weight::from_parts(0, 4721))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `AcurastHyperdriveIbc::IncomingMessages` (r:1 w:1)
	/// Proof: `AcurastHyperdriveIbc::IncomingMessages` (`max_values`: None, `max_size`: Some(1242), added: 3717, mode: `MaxEncodedLen`)
	/// Storage: `ParachainInfo::ParachainId` (r:1 w:0)
	/// Proof: `ParachainInfo::ParachainId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::OraclePublicKeys` (r:1 w:0)
	/// Proof: `AcurastHyperdriveIbc::OraclePublicKeys` (`max_values`: None, `max_size`: Some(58), added: 2533, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::IncomingMessagesLookup` (r:0 w:1)
	/// Proof: `AcurastHyperdriveIbc::IncomingMessagesLookup` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	fn receive_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `192`
		//  Estimated: `4707`
		// Minimum execution time: 35_800_000 picoseconds.
		Weight::from_parts(37_780_000, 0)
			.saturating_add(Weight::from_parts(0, 4707))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `AcurastHyperdriveIbc::IncomingMessages` (r:50 w:50)
	/// Proof: `AcurastHyperdriveIbc::IncomingMessages` (`max_values`: None, `max_size`: Some(1242), added: 3717, mode: `MaxEncodedLen`)
	/// Storage: `AcurastHyperdriveIbc::IncomingMessagesLookup` (r:0 w:50)
	/// Proof: `AcurastHyperdriveIbc::IncomingMessagesLookup` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 50]`.
	fn clean_incoming(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `67 + x * (202 ±0)`
		//  Estimated: `990 + x * (3717 ±0)`
		// Minimum execution time: 15_440_000 picoseconds.
		Weight::from_parts(3_817_626, 0)
			.saturating_add(Weight::from_parts(0, 990))
			// Standard Error: 9_482
			.saturating_add(Weight::from_parts(8_881_956, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(x.into())))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(x.into())))
			.saturating_add(Weight::from_parts(0, 3717).saturating_mul(x.into()))
	}
}
