
//! Autogenerated weights for `pallet_acurast_candidate_preselection`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `4a94f6a4994d`, CPU: `AMD EPYC 4244P 6-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("acurast-mainnet")`, DB CACHE: 1024

// Executed Command:
// /usr/local/bin/acurast-node
// benchmark
// pallet
// --chain=acurast-mainnet
// --wasm-execution=compiled
// --heap-pages=2048
// --pallet
// *
// --extrinsic
// *
// --steps=50
// --repeat=20
// --output=/bench/benchmarks/

// NOTE: `ref_time` values below were scaled by 3/2 after generation by
// ci/benchmark.sh, to compensate for benchmarking hardware measuring ~1.5x the
// Polkadot validator reference minimums. `proof_size` and DbWeight are unscaled.
// The unscaled measurements remain in the "Minimum execution time" comments.
#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_acurast_candidate_preselection`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_acurast_candidate_preselection::WeightInfo for WeightInfo<T> {
	/// Storage: `AcurastCandidatePreselection::CandidatePreselectionList` (r:0 w:1)
	/// Proof: `AcurastCandidatePreselection::CandidatePreselectionList` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_candidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_431_000 picoseconds.
		Weight::from_parts(9_288_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AcurastCandidatePreselection::CandidatePreselectionList` (r:0 w:1)
	/// Proof: `AcurastCandidatePreselection::CandidatePreselectionList` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_candidate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_410_000 picoseconds.
		Weight::from_parts(9_121_500, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
