
//! Autogenerated weights for `pallet_timestamp`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-10-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `1fbbe1a025d8`, CPU: `AMD EPYC 4244P 6-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("acurast-mainnet")`, DB CACHE: 1024

// Executed Command:
// /usr/local/bin/acurast-node
// benchmark
// pallet
// --chain=acurast-mainnet
// --wasm-execution=compiled
// --heap-pages=2048
// --pallet
// *
// --extrinsic
// *
// --steps=50
// --repeat=20
// --log=runtime::storage_reclaim_pallet=off,runtime::xcmp-queue-migration=off,pallet_collator_selection=off,xcm::benchmarking=off,acurast_mainnet_runtime::apis=off,acurast_kusama_runtime::apis=off,acurast_rococo_runtime::apis=off
// --output=/bench/benchmarks/

// NOTE: `ref_time` values below were scaled by 3/2 after generation by
// ci/benchmark.sh, to compensate for benchmarking hardware measuring ~1.5x the
// Polkadot validator reference minimums. `proof_size` and DbWeight are unscaled.
// The unscaled measurements remain in the "Minimum execution time" comments.
#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_timestamp`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_timestamp::WeightInfo for WeightInfo<T> {
	/// Storage: `Timestamp::Now` (r:1 w:1)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Aura::CurrentSlot` (r:1 w:0)
	/// Proof: `Aura::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `1493`
		// Minimum execution time: 5_249_000 picoseconds.
		Weight::from_parts(8_851_500, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn on_finalize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 821_000 picoseconds.
		Weight::from_parts(2_133_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
}
