
//! Autogenerated weights for `pallet_acurast`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-06-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `acurast-benchmark`, CPU: `AMD EPYC 7B13`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("acurast-kusama")`, DB CACHE: 1024

// Executed Command:
// /acurast-node
// benchmark
// pallet
// --chain=acurast-kusama
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// *
// --extrinsic
// *
// --steps=50
// --repeat=20
// --output=/benchmarks/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_acurast`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_acurast::WeightInfo for WeightInfo<T> {
	/// Storage: `Acurast::LocalJobIdSequence` (r:1 w:1)
	/// Proof: `Acurast::LocalJobIdSequence` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::StoredJobStatus` (r:1 w:1)
	/// Proof: `AcurastMarketplace::StoredJobStatus` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::StoredAdvertisementRestriction` (r:1 w:0)
	/// Proof: `AcurastMarketplace::StoredAdvertisementRestriction` (`max_values`: None, `max_size`: Some(3830), added: 6305, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::StoredAdvertisementPricing` (r:1 w:0)
	/// Proof: `AcurastMarketplace::StoredAdvertisementPricing` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::StoredStorageCapacity` (r:1 w:1)
	/// Proof: `AcurastMarketplace::StoredStorageCapacity` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::StoredMatches` (r:2 w:1)
	/// Proof: `AcurastMarketplace::StoredMatches` (`max_values`: None, `max_size`: Some(345), added: 2820, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::StoredTotalAssignedV3` (r:1 w:1)
	/// Proof: `AcurastMarketplace::StoredTotalAssignedV3` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::JobBudgets` (r:1 w:1)
	/// Proof: `AcurastMarketplace::JobBudgets` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::AssignedProcessors` (r:0 w:1)
	/// Proof: `AcurastMarketplace::AssignedProcessors` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// Storage: `Acurast::StoredJobRegistration` (r:0 w:1)
	/// Proof: `Acurast::StoredJobRegistration` (`max_values`: None, `max_size`: Some(34796), added: 37271, mode: `MaxEncodedLen`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `669`
		//  Estimated: `7295`
		// Minimum execution time: 140_371_000 picoseconds.
		Weight::from_parts(142_380_000, 0)
			.saturating_add(Weight::from_parts(0, 7295))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `AcurastMarketplace::StoredJobStatus` (r:1 w:1)
	/// Proof: `AcurastMarketplace::StoredJobStatus` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Acurast::StoredJobRegistration` (r:1 w:1)
	/// Proof: `Acurast::StoredJobRegistration` (`max_values`: None, `max_size`: Some(34796), added: 37271, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::JobBudgets` (r:1 w:1)
	/// Proof: `AcurastMarketplace::JobBudgets` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn deregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `899`
		//  Estimated: `38261`
		// Minimum execution time: 103_800_000 picoseconds.
		Weight::from_parts(106_960_000, 0)
			.saturating_add(Weight::from_parts(0, 38261))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Acurast::StoredJobRegistration` (r:1 w:1)
	/// Proof: `Acurast::StoredJobRegistration` (`max_values`: None, `max_size`: Some(34796), added: 37271, mode: `MaxEncodedLen`)
	/// Storage: `AcurastMarketplace::StoredJobStatus` (r:1 w:0)
	/// Proof: `AcurastMarketplace::StoredJobStatus` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 1000]`.
	fn update_allowed_sources(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `635`
		//  Estimated: `38261`
		// Minimum execution time: 36_940_000 picoseconds.
		Weight::from_parts(37_780_000, 0)
			.saturating_add(Weight::from_parts(0, 38261))
			// Standard Error: 19_523
			.saturating_add(Weight::from_parts(1_741_817, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Acurast::StoredRevokedCertificate` (r:4 w:0)
	/// Proof: `Acurast::StoredRevokedCertificate` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	/// Storage: `Acurast::StoredAttestation` (r:0 w:1)
	/// Proof: `Acurast::StoredAttestation` (`max_values`: None, `max_size`: Some(11622), added: 14097, mode: `MaxEncodedLen`)
	fn submit_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `208`
		//  Estimated: `11038`
		// Minimum execution time: 17_097_827_000 picoseconds.
		Weight::from_parts(17_140_688_000, 0)
			.saturating_add(Weight::from_parts(0, 11038))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Acurast::StoredRevokedCertificate` (r:0 w:1)
	/// Proof: `Acurast::StoredRevokedCertificate` (`max_values`: None, `max_size`: Some(37), added: 2512, mode: `MaxEncodedLen`)
	fn update_certificate_revocation_list() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 14_130_000 picoseconds.
		Weight::from_parts(14_830_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Acurast::StoredJobRegistration` (r:1 w:0)
	/// Proof: `Acurast::StoredJobRegistration` (`max_values`: None, `max_size`: Some(34796), added: 37271, mode: `MaxEncodedLen`)
	/// Storage: `Acurast::ExecutionEnvironment` (r:0 w:1)
	/// Proof: `Acurast::ExecutionEnvironment` (`max_values`: None, `max_size`: Some(10743), added: 13218, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 10]`.
	fn set_environment(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `365`
		//  Estimated: `38261`
		// Minimum execution time: 26_480_000 picoseconds.
		Weight::from_parts(27_276_194, 0)
			.saturating_add(Weight::from_parts(0, 38261))
			// Standard Error: 4_848
			.saturating_add(Weight::from_parts(487_741, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
