[package]
name = "acurast-reputation"
authors = ["Papers AG"]
description = "Library to manage reputation for Acurast marketplace."
version = "0.2.0"
license = "MIT"
homepage = "https://docs.acurast.com/"
repository = "https://github.com/acurast"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "reputation"
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }

# Substrate
sp-core = { workspace = true }
sp-arithmetic = { workspace = true }

[dev-dependencies]
sp-core = { workspace = true }
hex-literal = { workspace = true }
rand = "0.8.5"

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "sp-core/std",
    "scale-info/std",
]
