[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"runtime",
	"emulations",
	"emulations/payments-emulation",
	"examples/proxy-parachain/runtime",
	"examples/proxy-parachain/node",
]
