[profile.release]
panic = "unwind"

[profile.release-with-debug]
inherits = "release"
debug = true


[workspace]
members = [
	"node",
	"runtime/acurast",
#	"emulations",
#	"emulations/payments-emulation",
#	"examples/proxy-parachain/runtime",
#	"examples/proxy-parachain/node",
]

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[patch."https://github.com/Acurast/acurast-core.git"]
pallet-acurast-marketplace = { path = "../acurast-core/pallets/marketplace" }
pallet-acurast = { path = "../acurast-core/pallets/acurast" }