[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"runtime",
	"emulations",
	"examples/proxy-parachain/runtime",
	"examples/proxy-parachain/node",
]

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
