[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"pallets/*",
	"runtime",
]

[patch.'https://github.com/paritytech/substrate']
frame-benchmarking = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
frame-benchmarking-cli = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-transaction-payment-rpc = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-basic-authorship = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-chain-spec = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-cli = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-client-api = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-consensus = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-executor = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-network = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-rpc = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-rpc-api = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-service = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-sysinfo = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-telemetry = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-tracing = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-transaction-pool = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-transaction-pool-api = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-api = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-block-builder = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-blockchain = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-consensus = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-consensus-aura = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-inherents = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-offchain = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-session = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-timestamp = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-transaction-pool = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
substrate-frame-rpc-system = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
substrate-prometheus-endpoint = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
try-runtime-cli = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
substrate-build-script-utils = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
frame-executive = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
frame-support = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
frame-system = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
frame-system-benchmarking = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", optional = true, branch = "feat/p256" }
frame-system-rpc-runtime-api = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
frame-try-runtime = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", optional = true, branch = "feat/p256" }
pallet-aura = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-authorship = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-balances = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-session = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-sudo = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-timestamp = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-transaction-payment = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-transaction-payment-rpc-runtime-api = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-version = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
substrate-wasm-builder = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-core = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-keystore = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-runtime = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-io = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-std = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-runtime-interface = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-application-crypto = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-state-machine = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-storage = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-tasks = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-keystore = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-elections-phragmen = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-npos-elections = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
frame-election-provider-support = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-gilt = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-client-db = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-election-provider-multi-phase = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-consensus-aura = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-finality-grandpa = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-externalities = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-executor-common = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-executor-wasmtime = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
beefy-gadget = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-arithmetic = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-finality-grandpa = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
beefy-primitives = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-authority-discovery = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
babe = { package = "sc-consensus-babe", git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-block-builder = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-consensus-uncles = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-consensus-slots = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-sync-state-rpc = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-offchain = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-authority-discovery = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-trie = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-consensus-babe = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-babe = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-im-online = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
pallet-staking = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sc-consensus-epochs = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-consensus-vrf = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-staking = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-consensus-slots = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }
sp-mmr-primitives = { git = "ssh://git@gitlab.papers.tech:10022/papers/acurast/substrate.git", branch = "feat/p256" }