[profile.release]
panic = "unwind"

[workspace]
members = [
	"node",
	"runtime",
#	"emulations",
#	"emulations/payments-emulation",
]

[patch."https://github.com/Acurast/acurast-core.git"]
pallet-acurast = { path = "../acurast-core/pallets/acurast" }