[workspace]

[package]
name = "vara-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs = "0.3.0"
gstd = "*"
codec = { package = "parity-scale-codec", version = "3.6", default-features = false }
scale-info = { version = "2.11", default-features = false, features = [
	"derive",
] }
acurast-hyperdrive-substrate-core = { path = "../../substrate-core", default-features = false }
vara-ibc-client = { path = "../vara-ibc/client" }
blake2b_simd = { version = "1.0.2", default-features = false }

[build-dependencies]
sails-rs = { version = "0.3.0", features = ["wasm-builder"] }

[dev-dependencies]
vara-proxy = { path = ".", features = ["wasm-binary"] }
vara-proxy-client = { path = "client" }
tokio = { version = "1.39", features = ["rt", "macros"] }

[features]
wasm-binary = []
