[package]
name = "vara-ibc-idl"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = { version = "0.12", optional = true }
sails-rs = "0.3.0"

[build-dependencies]
vara-ibc = { path = ".." }
sails-idl-gen = "0.3.0"

[features]
mocks = ["sails-rs/mockall", "dep:mockall"]
