[workspace]
members = [
    "proxy",
    "state",
    "validator",
    "consumer",
    "ibc-ink-4",
    "ibc-ink-5"
]
resolver ="1"

[profile.release]
overflow-checks = false     # Disable integer overflow checks.
