[package]
name = "frame-support-procedural"
version = "30.0.3"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Proc macro of Support code for the runtime."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = { version = "0.2.0" }
docify = { version = "0.2.8" }
Inflector = { version = "0.11.4" }
cfg-expr = { version = "0.15.5" }
itertools = { version = "0.11" }
proc-macro2 = { version = "1.0.64" }
quote = { version = "1.0.37" }
syn = { version = "2.0.65", features = ["full", "parsing", "visit-mut"] }
frame-support-procedural-tools = { git = "https://github.com/paritytech/polkadot-sdk", default-features = true, tag = "polkadot-v1.16.2" }
macro_magic = { version = "0.5.1", features = ["proc_support"] }
proc-macro-warning = { version = "1.0.0", default-features = false }
expander = { version = "2.0.0" }
sp-crypto-hashing = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.16.2" }

[dev-dependencies]
codec = { version = "3.6.12", features = [
	"derive",
	"max-encoded-len",
], default-features = false, package = "parity-scale-codec" }
regex = { version = "1.10.2" }
sp-metadata-ir = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.16.2" }
scale-info = { version = "2.11.1", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.16.2" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.16.2" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", features = [
	"serde",
], default-features = false, tag = "polkadot-v1.16.2" }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.16.2" }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.16.2" }
pretty_assertions = { version = "1.3.0" }
static_assertions = { version = "1.1.0", default-features = false }

[features]
default = ["std"]
std = ["sp-crypto-hashing/std"]
no-metadata-docs = []
experimental = []
# Generate impl-trait for tuples with the given number of tuples. Will be needed as the number of
# pallets in a runtime grows. Does increase the compile time!
tuples-96 = []
tuples-128 = []
allow-faucet = []

[[example]]
name = "proc_main"
