[package]
name = "frame-support-procedural"
version = "33.0.1"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Proc macro of Support code for the runtime."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
Inflector = { version = "0.11.4" }
cfg-expr = { version = "0.15.5" }
derive-syn-parse = { version = "0.2.0" }
docify = { version = "0.2.9" }
expander = { version = "2.0.0" }
frame-support-procedural-tools = { git = "https://github.com/paritytech/polkadot-sdk", default-features = true, tag = "polkadot-v1.18.5" }
itertools = { version = "0.11" }
macro_magic = { version = "0.5.1", features = ["proc_support"] }
proc-macro-warning = { version = "1.0.0", default-features = false }
proc-macro2 = { version = "1.0.86" }
quote = { version = "1.0.37" }
sp-crypto-hashing = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.18.5" }
syn = { version = "2.0.87", features = ["full", "parsing", "visit-mut"] }

[dev-dependencies]
parity-scale-codec = { features = [
	"derive",
	"max-encoded-len",
], workspace = true }
frame-support = { default-features = false, workspace = true }
frame-system = { default-features = false, workspace = true }
pretty_assertions = { version = "1.3.0" }
regex = { version = "1.10.2" }
scale-info = { features = ["derive"], workspace = true }
sp-core = { default-features = false, workspace = true }
sp-io = { default-features = false, workspace = true }
sp-metadata-ir = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.18.5" }
sp-runtime = { features = [
	"serde",
], default-features = false, workspace = true }
static_assertions = { version = "1.1.0", default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-crypto-hashing/std",
	"sp-io/std",
	"sp-metadata-ir/std",
	"sp-runtime/std",
]
no-metadata-docs = []
experimental = []
# Generate impl-trait for tuples with the given number of tuples. Will be needed as the number of
# pallets in a runtime grows. Does increase the compile time!
tuples-96 = []
tuples-128 = []
allow-faucet = []

[[example]]
name = "proc_main"
